# Generated by Django 3.1.1 on 2020-11-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imall', '0002_auto_20201028_2201'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Product_id', models.AutoField(primary_key=True, serialize=False)),
                ('Product_name', models.CharField(max_length=255)),
                ('Product_desc', models.CharField(max_length=500)),
            ],
        ),
    ]
