# Generated by Django 3.1.1 on 2020-11-01 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imall', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_desc',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='product',
            name='Product_name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
