# Generated by Django 3.1.1 on 2020-12-14 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imall', '0004_auto_20201101_1113'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Product_mrp',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='discount_per',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='Media/'),
        ),
    ]
