# Generated by Django 3.1.1 on 2020-12-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imall', '0005_auto_20201214_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(default='', max_length=255),
        ),
    ]
