# Generated by Django 3.1.1 on 2020-12-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imall', '0006_product_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='', upload_to='imall/images'),
        ),
    ]
